-- ===========================================================================
-- Evollo · ETAPA 3 — USUARIOS E ACESSOS (administracao)
-- ---------------------------------------------------------------------------
-- Constroi o que falta para uma pessoa que NAO e o proprietario entrar no
-- painel: convite por codigo, vinculo, perfil, excecao individual, bloqueio e
-- auditoria.
--
-- NAO MIGRA POLICY NENHUMA. As 136 antigas continuam com `nutri_id =
-- auth.uid()`. O segundo usuario vai entrar, ver o menu certo e NAO ver
-- paciente — isso e esperado, e e exatamente o que a Etapa 4 resolve.
--
-- NAO ALTERA db/organizacao_schema.sql. Nada da Etapa 2 e tocado
-- retroativamente: o cadastro pendente mora em tabela propria, e nao numa
-- coluna nova de organizacao_usuarios.
--
-- Desfazer: db/organizacao_usuarios_admin_desfazer.sql
-- Conferir: db/conferencia/74_usuarios_acessos.sql
-- Rodar no SQL Editor do Supabase.
-- ===========================================================================


-- ===========================================================================
-- 1) CONVITES
-- ---------------------------------------------------------------------------
-- POR QUE TABELA PROPRIA, E NAO UMA LINHA "PENDENTE" EM organizacao_usuarios.
-- Um convite nao e um usuario. Ele expira, e revogavel, e de uso unico e tem
-- autor — nada disso pertence a quem TEM acesso. Separando, a pergunta "quem
-- entra na minha organizacao?" continua com uma resposta so, e o convite nao
-- precisa de auth_user_id nulo nem de um terceiro status.
--
-- O codigo NAO reaproveita nenhum dos tres que ja existem no projeto:
--   pacientes.codigo         abre a anamnese publica
--   funcionarios.codigo_acesso  vincula colaborador ao app da equipe
--   codigos_convite.codigo   cria organizacao nova (nivel SaaS)
-- Significados diferentes; misturar seria dar a um o poder do outro.
-- ===========================================================================

create table if not exists public.organizacao_convites (
  id             uuid primary key default gen_random_uuid(),
  organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
  nome           text not null,
  email          text not null,
  perfil_id      uuid not null references public.perfis(id) on delete restrict,
  funcionario_id uuid references public.funcionarios(id) on delete set null,
  codigo         text not null,
  expira_em      timestamptz not null default now() + interval '14 days',
  revogado_em    timestamptz,
  usado_em       timestamptz,
  usado_por      uuid references auth.users(id) on delete set null,
  criado_por     uuid default auth.uid() references auth.users(id) on delete set null,
  criado_em      timestamptz not null default now()
);

-- Unico GLOBAL e por upper(): o vinculo procura o codigo sem saber de que
-- organizacao ele e, entao dois iguais em organizacoes diferentes tornariam a
-- busca ambigua.
create unique index if not exists uq_org_convite_codigo
  on public.organizacao_convites (upper(codigo));

create index if not exists idx_org_convite_org
  on public.organizacao_convites (organizacao_id, criado_em desc);

-- Um convite ABERTO por e-mail e organizacao. Convite usado ou revogado sai da
-- conta — reconvidar depois de revogar tem que funcionar.
create unique index if not exists uq_org_convite_email_aberto
  on public.organizacao_convites (organizacao_id, lower(email))
  where usado_em is null and revogado_em is null;


-- ===========================================================================
-- 2) AUDITORIA DA ADMINISTRACAO DE USUARIOS
-- ---------------------------------------------------------------------------
-- Segue a convencao das quatro auditorias que ja existem: DONO e AUTOR em
-- colunas separadas. Aqui a distincao finalmente tem valor pratico — ate agora
-- as duas guardavam a mesma pessoa.
-- ===========================================================================

create table if not exists public.organizacao_auditoria (
  id             bigint generated by default as identity primary key,
  organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
  usuario_alvo   uuid,
  usuario_autor  uuid not null default auth.uid(),
  acao           text not null,
  antes          jsonb,
  depois         jsonb,
  criado_em      timestamptz not null default now()
);

alter table public.organizacao_auditoria drop constraint if exists organizacao_auditoria_acao_check;
alter table public.organizacao_auditoria add  constraint organizacao_auditoria_acao_check
  check (acao in ('codigo_gerado', 'codigo_revogado', 'vinculo_realizado',
                  'perfil_alterado', 'permissao_alterada',
                  'usuario_bloqueado', 'usuario_reativado'));

create index if not exists idx_org_auditoria
  on public.organizacao_auditoria (organizacao_id, criado_em desc);


-- ===========================================================================
-- 3) GERADOR DE CODIGO
-- ---------------------------------------------------------------------------
-- SECURITY DEFINER de proposito, e a licao vem do proprio projeto:
-- gerar_codigo_paciente() e INVOKER e so enxerga os proprios pacientes ao
-- testar unicidade, enquanto o codigo e unico GLOBAL. Com duas organizacoes,
-- ela gera codigo repetido. Aqui a funcao ve a tabela inteira.
--
-- Alfabeto sem 0/O/1/I/L: o codigo vai ser ditado por telefone e digitado a mao.
-- ===========================================================================

create or replace function public.gerar_codigo_organizacao()
returns text
language plpgsql
volatile
security definer
set search_path = public
as $fn$
declare
  alfabeto   text := 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
  v_codigo   text;
  i          integer;
  tentativas integer := 0;
begin
  loop
    v_codigo := 'EVL-';
    for i in 1..5 loop
      v_codigo := v_codigo || substr(alfabeto, 1 + floor(random() * length(alfabeto))::int, 1);
    end loop;

    if not exists (select 1 from public.organizacao_convites where upper(codigo) = v_codigo) then
      return v_codigo;
    end if;

    tentativas := tentativas + 1;
    if tentativas > 20 then
      raise exception 'nao_foi_possivel_gerar_codigo';
    end if;
  end loop;
end $fn$;


-- ===========================================================================
-- 4) TRAVA DO ULTIMO PROPRIETARIO
-- ---------------------------------------------------------------------------
-- NO BANCO, e nao so nas RPCs. E o que atende ao "mesmo que a UI tenha bug":
-- qualquer caminho — RPC, SQL Editor, script futuro — esbarra aqui.
--
-- Permite transferir a propriedade: promover outra pessoa a proprietario e,
-- so depois, rebaixar a primeira. O que ela impede e a organizacao ficar sem
-- nenhum proprietario ATIVO.
-- ===========================================================================

create or replace function public.fn_protege_ultimo_proprietario()
returns trigger
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_era_prop  boolean;
  v_sera_prop boolean;
  v_restantes integer;
begin
  select exists (select 1 from public.perfis p
                  where p.id = old.perfil_id and p.chave = 'proprietario')
    into v_era_prop;

  -- Linha que nao era proprietario ativo nao pode deixar a organizacao sem um.
  if not v_era_prop or old.status <> 'ativo' then
    if tg_op = 'DELETE' then return old; else return new; end if;
  end if;

  if tg_op = 'UPDATE' then
    select exists (select 1 from public.perfis p
                    where p.id = new.perfil_id and p.chave = 'proprietario')
      into v_sera_prop;
    -- Continua proprietario ativo: nada mudou do ponto de vista da trava.
    if v_sera_prop and new.status = 'ativo' then
      return new;
    end if;
  end if;

  select count(*) into v_restantes
    from public.organizacao_usuarios ou
    join public.perfis p on p.id = ou.perfil_id
   where ou.organizacao_id = old.organizacao_id
     and p.chave = 'proprietario'
     and ou.status = 'ativo'
     and ou.id <> old.id;

  if v_restantes = 0 then
    raise exception 'ultimo_proprietario';
  end if;

  if tg_op = 'DELETE' then return old; else return new; end if;
end $fn$;

drop trigger if exists trg_protege_ultimo_proprietario on public.organizacao_usuarios;
create trigger trg_protege_ultimo_proprietario
  before update or delete on public.organizacao_usuarios
  for each row execute function public.fn_protege_ultimo_proprietario();


-- ===========================================================================
-- 5) RPCs ADMINISTRATIVAS
-- ---------------------------------------------------------------------------
-- TODAS sao SECURITY DEFINER, entao TODAS passam por cima da RLS. Cada uma
-- precisa conferir organizacao E permissao por conta propria — esquecer numa
-- e vazar entre organizacoes. E o ponto mais delicado desta etapa, e por isso
-- a primeira linha de cada uma e sempre a mesma checagem.
--
-- Os erros sao codigos curtos, na convencao que vincular_funcionario() ja usa:
-- o front traduz para portugues. Mensagem de banco nao e frase de gente.
-- ===========================================================================

-- Guarda comum: devolve a organizacao do autor, ou estoura.
create or replace function public.exige_permissao(p_chave text)
returns uuid
language plpgsql
stable
security definer
set search_path = public
as $fn$
declare
  v_org uuid;
begin
  if auth.uid() is null then
    raise exception 'precisa_estar_logado';
  end if;
  v_org := public.organizacao_do_auth();
  if v_org is null then
    raise exception 'sem_organizacao';
  end if;
  if not public.tem_permissao(p_chave) then
    raise exception 'sem_permissao';
  end if;
  return v_org;
end $fn$;


create or replace function public.usuario_convidar(
  p_nome           text,
  p_email          text,
  p_perfil_chave   text,
  p_funcionario_id uuid default null
)
returns text
language plpgsql
volatile
security definer
set search_path = public
as $fn$
declare
  v_org    uuid;
  v_perfil uuid;
  v_codigo text;
  v_id     uuid;
begin
  v_org := public.exige_permissao('usuarios.gerenciar');

  if coalesce(btrim(p_nome), '') = '' or coalesce(btrim(p_email), '') = '' then
    raise exception 'nome_e_email_obrigatorios';
  end if;

  -- Proprietario NAO nasce por convite. Elevar alguem a proprietario e acao
  -- administrativa separada, e vai precisar de outra trava.
  if p_perfil_chave = 'proprietario' then
    raise exception 'perfil_proprietario_nao_permitido';
  end if;

  select id into v_perfil
    from public.perfis
   where chave = p_perfil_chave
     and ativo
     and (organizacao_id is null or organizacao_id = v_org);
  if v_perfil is null then
    raise exception 'perfil_invalido';
  end if;

  -- O funcionario, se informado, tem que ser da mesma organizacao. Sem isto,
  -- daria para amarrar um usuario ao colaborador de outra empresa.
  if p_funcionario_id is not null
     and not exists (select 1 from public.funcionarios f
                      where f.id = p_funcionario_id and f.nutri_id = v_org) then
    raise exception 'funcionario_de_outra_organizacao';
  end if;

  if exists (select 1 from public.organizacao_usuarios ou
              join auth.users u on u.id = ou.auth_user_id
             where ou.organizacao_id = v_org and lower(u.email) = lower(btrim(p_email))) then
    raise exception 'email_ja_e_membro';
  end if;

  v_codigo := public.gerar_codigo_organizacao();

  insert into public.organizacao_convites
    (organizacao_id, nome, email, perfil_id, funcionario_id, codigo)
  values
    (v_org, btrim(p_nome), lower(btrim(p_email)), v_perfil, p_funcionario_id, v_codigo)
  returning id into v_id;

  insert into public.organizacao_auditoria (organizacao_id, usuario_alvo, acao, depois)
  values (v_org, v_id, 'codigo_gerado',
          jsonb_build_object('nome', btrim(p_nome), 'email', lower(btrim(p_email)),
                             'perfil', p_perfil_chave));

  return v_codigo;
end $fn$;


create or replace function public.usuario_vincular(p_codigo text)
returns uuid
language plpgsql
volatile
security definer
set search_path = public
as $fn$
declare
  c        public.organizacao_convites%rowtype;
  v_email  text;
  v_id     uuid;
begin
  if auth.uid() is null then
    raise exception 'precisa_estar_logado';
  end if;

  if exists (select 1 from public.organizacao_usuarios where auth_user_id = auth.uid()) then
    raise exception 'conta_ja_vinculada';
  end if;

  select * into c from public.organizacao_convites
   where upper(codigo) = upper(btrim(p_codigo));

  if c.id is null                    then raise exception 'codigo_invalido'; end if;
  if c.revogado_em is not null       then raise exception 'codigo_revogado'; end if;
  if c.usado_em is not null          then raise exception 'codigo_usado';    end if;
  if c.expira_em < now()             then raise exception 'codigo_expirado'; end if;

  if not exists (select 1 from public.organizacoes o
                  where o.id = c.organizacao_id and o.ativo) then
    raise exception 'organizacao_inativa';
  end if;

  -- E-MAIL COMPATIVEL. Sem isto o codigo sozinho e a credencial: quem o
  -- interceptar entra na organizacao. Com isto ele so vale para quem foi
  -- convidado, e um codigo vazado nao serve para mais ninguem.
  select lower(u.email) into v_email from auth.users u where u.id = auth.uid();
  if v_email is distinct from lower(c.email) then
    raise exception 'email_diferente_do_convite';
  end if;

  insert into public.organizacao_usuarios
    (organizacao_id, auth_user_id, nome, perfil_id, funcionario_id, status)
  values
    (c.organizacao_id, auth.uid(), c.nome, c.perfil_id, c.funcionario_id, 'ativo')
  returning id into v_id;

  update public.organizacao_convites
     set usado_em = now(), usado_por = auth.uid()
   where id = c.id;

  insert into public.organizacao_auditoria (organizacao_id, usuario_alvo, acao, depois)
  values (c.organizacao_id, v_id, 'vinculo_realizado',
          jsonb_build_object('email', v_email, 'convite', c.id));

  return v_id;
end $fn$;


create or replace function public.usuario_definir_perfil(p_usuario_id uuid, p_perfil_id uuid)
returns void
language plpgsql
volatile
security definer
set search_path = public
as $fn$
declare
  v_org    uuid;
  v_antes  uuid;
  v_chave  text;
begin
  v_org := public.exige_permissao('usuarios.gerenciar');

  select perfil_id into v_antes
    from public.organizacao_usuarios
   where id = p_usuario_id and organizacao_id = v_org;
  if v_antes is null then
    raise exception 'usuario_nao_encontrado';
  end if;

  select chave into v_chave
    from public.perfis
   where id = p_perfil_id and ativo
     and (organizacao_id is null or organizacao_id = v_org);
  if v_chave is null then
    raise exception 'perfil_invalido';
  end if;
  if v_chave = 'proprietario' then
    raise exception 'perfil_proprietario_nao_permitido';
  end if;

  -- A trava do ultimo proprietario mora no trigger: se esta linha for o unico
  -- proprietario ativo, o update abaixo estoura com 'ultimo_proprietario'.
  update public.organizacao_usuarios
     set perfil_id = p_perfil_id
   where id = p_usuario_id and organizacao_id = v_org;

  insert into public.organizacao_auditoria (organizacao_id, usuario_alvo, acao, antes, depois)
  values (v_org, p_usuario_id, 'perfil_alterado',
          jsonb_build_object('perfil_id', v_antes),
          jsonb_build_object('perfil_id', p_perfil_id, 'chave', v_chave));
end $fn$;


create or replace function public.usuario_definir_status(p_usuario_id uuid, p_status text)
returns void
language plpgsql
volatile
security definer
set search_path = public
as $fn$
declare
  v_org   uuid;
  v_antes text;
begin
  v_org := public.exige_permissao('usuarios.gerenciar');

  if p_status not in ('ativo', 'bloqueado') then
    raise exception 'status_invalido';
  end if;

  select status into v_antes
    from public.organizacao_usuarios
   where id = p_usuario_id and organizacao_id = v_org;
  if v_antes is null then
    raise exception 'usuario_nao_encontrado';
  end if;

  -- Ninguem se bloqueia. Sem isto, o unico administrador se tranca do lado de
  -- fora e ninguem mais consegue reativar.
  if p_status = 'bloqueado'
     and exists (select 1 from public.organizacao_usuarios
                  where id = p_usuario_id and auth_user_id = auth.uid()) then
    raise exception 'nao_pode_bloquear_a_si_mesmo';
  end if;

  update public.organizacao_usuarios
     set status = p_status
   where id = p_usuario_id and organizacao_id = v_org;

  insert into public.organizacao_auditoria (organizacao_id, usuario_alvo, acao, antes, depois)
  values (v_org, p_usuario_id,
          case when p_status = 'bloqueado' then 'usuario_bloqueado' else 'usuario_reativado' end,
          jsonb_build_object('status', v_antes),
          jsonb_build_object('status', p_status));
end $fn$;


-- p_modo: 'perfil' apaga a excecao | 'permitir' concede | 'bloquear' revoga.
-- Permissao herdada NAO vira linha: o padrao do perfil e a ausencia.
create or replace function public.usuario_definir_permissao(
  p_usuario_id uuid, p_chave text, p_modo text
)
returns void
language plpgsql
volatile
security definer
set search_path = public
as $fn$
declare
  v_org   uuid;
  v_antes text;
begin
  v_org := public.exige_permissao('usuarios.gerenciar');

  if p_modo not in ('perfil', 'permitir', 'bloquear') then
    raise exception 'modo_invalido';
  end if;
  if not exists (select 1 from public.permissoes where chave = p_chave) then
    raise exception 'permissao_invalida';
  end if;
  if not exists (select 1 from public.organizacao_usuarios
                  where id = p_usuario_id and organizacao_id = v_org) then
    raise exception 'usuario_nao_encontrado';
  end if;

  select case when concede then 'permitir' else 'bloquear' end into v_antes
    from public.usuario_permissoes
   where usuario_id = p_usuario_id and permissao_chave = p_chave;

  if p_modo = 'perfil' then
    delete from public.usuario_permissoes
     where usuario_id = p_usuario_id and permissao_chave = p_chave;
  else
    insert into public.usuario_permissoes (usuario_id, permissao_chave, concede)
    values (p_usuario_id, p_chave, p_modo = 'permitir')
    on conflict (usuario_id, permissao_chave)
      do update set concede = excluded.concede;
  end if;

  insert into public.organizacao_auditoria (organizacao_id, usuario_alvo, acao, antes, depois)
  values (v_org, p_usuario_id, 'permissao_alterada',
          jsonb_build_object('chave', p_chave, 'modo', coalesce(v_antes, 'perfil')),
          jsonb_build_object('chave', p_chave, 'modo', p_modo));
end $fn$;


create or replace function public.usuario_convite_revogar(p_convite_id uuid)
returns void
language plpgsql
volatile
security definer
set search_path = public
as $fn$
declare
  v_org uuid;
begin
  v_org := public.exige_permissao('usuarios.gerenciar');

  update public.organizacao_convites
     set revogado_em = now()
   where id = p_convite_id
     and organizacao_id = v_org
     and usado_em is null
     and revogado_em is null;

  if not found then
    raise exception 'convite_nao_encontrado';
  end if;

  insert into public.organizacao_auditoria (organizacao_id, usuario_alvo, acao)
  values (v_org, p_convite_id, 'codigo_revogado');
end $fn$;


-- ===========================================================================
-- 6) LEITURAS
-- ---------------------------------------------------------------------------
-- Sao RPC e nao `select` direto porque o E-MAIL mora em auth.users, que o
-- PostgREST nao expoe. Copiar o email para organizacao_usuarios criaria uma
-- segunda fonte que envelhece quando a pessoa troca de email no Auth.
-- ===========================================================================

create or replace function public.usuarios_da_organizacao()
returns table (
  id uuid, nome text, email text, perfil_chave text, perfil_nome text,
  status text, funcionario_nome text, ultimo_acesso_em timestamptz,
  e_proprietario boolean, sou_eu boolean, excecoes integer
)
language sql
stable
security definer
set search_path = public
as $fn$
  select
    ou.id, ou.nome, u.email, p.chave, p.nome,
    ou.status, f.nome, ou.ultimo_acesso_em,
    p.chave = 'proprietario',
    ou.auth_user_id = auth.uid(),
    (select count(*)::int from public.usuario_permissoes up where up.usuario_id = ou.id)
  from public.organizacao_usuarios ou
  join public.perfis p    on p.id = ou.perfil_id
  join auth.users u       on u.id = ou.auth_user_id
  left join public.funcionarios f on f.id = ou.funcionario_id
  where ou.organizacao_id = public.organizacao_do_auth()
    and public.tem_permissao('usuarios.visualizar')
  order by (p.chave = 'proprietario') desc, ou.nome;
$fn$;


create or replace function public.convites_pendentes()
returns table (
  id uuid, nome text, email text, perfil_nome text,
  codigo text, expira_em timestamptz, expirado boolean, criado_em timestamptz
)
language sql
stable
security definer
set search_path = public
as $fn$
  select c.id, c.nome, c.email, p.nome, c.codigo, c.expira_em,
         c.expira_em < now(), c.criado_em
  from public.organizacao_convites c
  join public.perfis p on p.id = c.perfil_id
  where c.organizacao_id = public.organizacao_do_auth()
    and c.usado_em is null
    and c.revogado_em is null
    and public.tem_permissao('usuarios.gerenciar')
  order by c.criado_em desc;
$fn$;


-- As permissoes de UM usuario, com a origem de cada uma. E o que a tela do §14
-- precisa para dizer "Herdado" ou "Personalizado" sem o administrador ter que
-- entender perfil_permissoes e usuario_permissoes.
create or replace function public.permissoes_do_usuario(p_usuario_id uuid)
returns table (
  chave text, modulo text, acao text, descricao text, sensivel boolean, ordem integer,
  do_perfil boolean, modo text, efetiva boolean
)
language sql
stable
security definer
set search_path = public
as $fn$
  select
    pm.chave, pm.modulo, pm.acao, pm.descricao, pm.sensivel, pm.ordem,
    pp.permissao_chave is not null,
    case when up.permissao_chave is null then 'perfil'
         when up.concede then 'permitir' else 'bloquear' end,
    coalesce(up.concede, pp.permissao_chave is not null)
  from public.permissoes pm
  cross join public.organizacao_usuarios ou
  left join public.perfil_permissoes pp
    on pp.perfil_id = ou.perfil_id and pp.permissao_chave = pm.chave
  left join public.usuario_permissoes up
    on up.usuario_id = ou.id and up.permissao_chave = pm.chave
  where ou.id = p_usuario_id
    and ou.organizacao_id = public.organizacao_do_auth()
    and public.tem_permissao('usuarios.visualizar')
  order by pm.ordem;
$fn$;


-- Registra o proprio acesso. Sem isto a coluna ultimo_acesso_em nunca sai de
-- null e a coluna da tela nao significa nada.
create or replace function public.registrar_meu_acesso()
returns void
language sql
volatile
security definer
set search_path = public
as $fn$
  update public.organizacao_usuarios
     set ultimo_acesso_em = now()
   where auth_user_id = auth.uid() and status = 'ativo';
$fn$;


-- ===========================================================================
-- 7) CONTAS FORA DA ORGANIZACAO
-- ---------------------------------------------------------------------------
-- Diagnostico, nao gestao. Nao ha nenhuma acao que altere essas contas nesta
-- etapa — a tela mostra, e a decisao e administrativa.
--
-- NENHUMA policy nova em nutricionistas, e auth.users continua inacessivel
-- pela API. O unico caminho e esta funcao, atras de usuarios.gerenciar.
-- ===========================================================================

create or replace function public.contas_fora_da_organizacao()
returns table (
  user_id uuid, email text, nome text,
  criada_em timestamptz, ultimo_login timestamptz,
  e_admin boolean, pacientes integer
)
language sql
stable
security definer
set search_path = public
as $fn$
  select
    n.id, u.email, n.nome, u.created_at, u.last_sign_in_at,
    exists (select 1 from public.admins a where a.user_id = n.id),
    (select count(*)::int from public.pacientes p where p.nutri_id = n.id)
  from public.nutricionistas n
  join auth.users u on u.id = n.id
  where not exists (select 1 from public.organizacao_usuarios ou where ou.auth_user_id = n.id)
    and public.tem_permissao('usuarios.gerenciar')
  order by u.last_sign_in_at desc nulls last;
$fn$;


-- O detalhe do §23. Conta modulo a modulo: zero num modulo NAO significa zero
-- nos outros, e a decisao sobre a conta depende de saber onde ha dado.
--
-- AS TABELAS SAO DESCOBERTAS, NAO ESCRITAS A MAO.
--
-- A primeira versao listava as tabelas numa sequencia de `union all`, e ela
-- nao passou nem da primeira aplicacao: `public.checkin_ocorrencias` esta
-- versionada em db/checkin_schema.sql mas NAO existe no banco, e uma
-- referencia estatica a tabela inexistente derruba a funcao inteira no parse —
-- levando junto as outras quinze contagens, que estavam certas.
--
-- Aqui a lista sai de information_schema e a contagem e dinamica. Efeitos:
--   * tabela ausente simplesmente nao aparece, em vez de quebrar tudo;
--   * modulo novo entra sozinho, sem editar esta funcao;
--   * o que ha de dado e o que o banco TEM, nao o que o repositorio espera.
--
-- O format(%I) cita o identificador e o valor vai por `using`, entao nao ha
-- superficie de injecao — os nomes vem do catalogo, nao de quem chama.
create or replace function public.conta_externa_detalhe(p_user_id uuid)
returns table (grupo text, item text, valor text)
language plpgsql
stable
security definer
set search_path = public
as $fn$
declare
  r         record;
  v_qtd     bigint;
  v_tabelas integer := 0;
  v_com     integer := 0;
begin
  -- Tres portas, e todas fecham em silencio: quem nao pode gerenciar usuarios
  -- nao descobre nem que a conta existe.
  if not public.tem_permissao('usuarios.gerenciar') then return; end if;
  if not exists (select 1 from public.nutricionistas n where n.id = p_user_id) then return; end if;
  if exists (select 1 from public.organizacao_usuarios ou where ou.auth_user_id = p_user_id) then return; end if;

  return query
    select 'CONTA'::text, 'e-mail'::text, u.email::text
      from auth.users u where u.id = p_user_id;
  return query
    select 'CONTA'::text, 'nome'::text, coalesce(n.nome, '(sem nome)')::text
      from public.nutricionistas n where n.id = p_user_id;
  return query
    select 'CONTA'::text, 'criada em'::text, u.created_at::date::text
      from auth.users u where u.id = p_user_id;
  return query
    select 'CONTA'::text, 'ultimo login'::text,
           coalesce(u.last_sign_in_at::date::text, 'nunca entrou')
      from auth.users u where u.id = p_user_id;
  return query
    select 'CONTA'::text, 'e admin do SaaS'::text,
           case when exists (select 1 from public.admins a where a.user_id = p_user_id)
                then 'sim' else 'nao' end::text;
  return query
    select 'CONTA'::text, 'organizacao'::text, 'nenhuma'::text;

  for r in
    select c.table_name
      from information_schema.columns c
      join information_schema.tables t
        on t.table_schema = c.table_schema and t.table_name = c.table_name
     where c.table_schema = 'public'
       and c.column_name = 'nutri_id'
       and t.table_type = 'BASE TABLE'
     order by c.table_name
  loop
    execute format('select count(*) from public.%I where nutri_id = $1', r.table_name)
      into v_qtd using p_user_id;
    v_tabelas := v_tabelas + 1;
    if v_qtd > 0 then
      v_com := v_com + 1;
      return query select 'DADOS'::text, r.table_name::text, v_qtd::text;
    end if;
  end loop;

  -- A linha de fechamento e o §23 em uma frase: sem ela, uma lista curta se
  -- leria como "quase nao ha dado", quando pode ser "quase nao ha tabela".
  return query
    select 'DADOS'::text,
           '(' || v_tabelas || ' tabelas conferidas)'::text,
           case when v_com = 0 then 'nenhuma com dado desta conta'
                else v_com || ' com dado' end::text;

  return query
    select 'STORAGE'::text, 'objetos'::text,
           (select count(*)::text from storage.objects so
             where (storage.foldername(so.name))[1] = p_user_id::text);
end $fn$;


-- ===========================================================================
-- 8) RLS DAS TABELAS NOVAS
-- ---------------------------------------------------------------------------
-- As duas com RLS ativa e ZERO policies, como codigos_convite e
-- perfil_permissoes: nenhum papel alcanca pela API, so as funcoes DEFINER.
-- Convite e auditoria sao exatamente o tipo de dado que nao deve ter caminho
-- direto de leitura nem de escrita.
--
-- NAO usar `force row level security` — ver a nota em organizacao_do_auth().
-- ===========================================================================

alter table public.organizacao_convites  enable row level security;
alter table public.organizacao_auditoria enable row level security;


-- ===========================================================================
-- 9) ACL
-- ---------------------------------------------------------------------------
-- exige_permissao() e gerar_codigo_organizacao() sao INTERNAS: nao levam
-- execute para authenticated. Sao chamadas de dentro das outras funcoes, que
-- rodam como definer.
-- ===========================================================================

revoke all on function public.exige_permissao(text)              from public, anon, authenticated;
revoke all on function public.gerar_codigo_organizacao()         from public, anon, authenticated;
revoke all on function public.fn_protege_ultimo_proprietario()   from public, anon, authenticated;

revoke all on function public.usuario_convidar(text, text, text, uuid) from public, anon;
revoke all on function public.usuario_vincular(text)                   from public, anon;
revoke all on function public.usuario_definir_perfil(uuid, uuid)       from public, anon;
revoke all on function public.usuario_definir_status(uuid, text)       from public, anon;
revoke all on function public.usuario_definir_permissao(uuid, text, text) from public, anon;
revoke all on function public.usuario_convite_revogar(uuid)            from public, anon;
revoke all on function public.usuarios_da_organizacao()                from public, anon;
revoke all on function public.convites_pendentes()                     from public, anon;
revoke all on function public.permissoes_do_usuario(uuid)              from public, anon;
revoke all on function public.registrar_meu_acesso()                   from public, anon;
revoke all on function public.contas_fora_da_organizacao()             from public, anon;
revoke all on function public.conta_externa_detalhe(uuid)              from public, anon;

grant execute on function public.usuario_convidar(text, text, text, uuid) to authenticated;
grant execute on function public.usuario_vincular(text)                   to authenticated;
grant execute on function public.usuario_definir_perfil(uuid, uuid)       to authenticated;
grant execute on function public.usuario_definir_status(uuid, text)       to authenticated;
grant execute on function public.usuario_definir_permissao(uuid, text, text) to authenticated;
grant execute on function public.usuario_convite_revogar(uuid)            to authenticated;
grant execute on function public.usuarios_da_organizacao()                to authenticated;
grant execute on function public.convites_pendentes()                     to authenticated;
grant execute on function public.permissoes_do_usuario(uuid)              to authenticated;
grant execute on function public.registrar_meu_acesso()                   to authenticated;
grant execute on function public.contas_fora_da_organizacao()             to authenticated;
grant execute on function public.conta_externa_detalhe(uuid)              to authenticated;
